### PR TITLE
Migrate new assets to shared assets

### PR DESCRIPTION
**Pull request by bradymiller**
1st commit:
1. Updated assets from main codebase.

2nd commit:
1. migrated angular libraries to shared assets
2. migrated bootstrap-combobox library to shared assets
3. migrated checklist-model library to shared assets
4. migrated bootstrap-datetimepicker library to shared assets
5. migrated creditCardValidator library to shared assets
6. removed unused jquery.validate.js library (is at shared asset if need)
7. migrated emodal library to shared assets
8. migrated summernote library to shared assets

### CODE REVIEW

**Comment by bradymiller** [comment]
This is testing well and ready.

**Comment by bradymiller** [comment]
Working on another PR that combines this with other migrated assets, so will close this.

**Comment by sjpadgett** [comment]
You know this negated backwards compatibility with 4.2.2.

**Comment by bradymiller** [comment]
Here's the better PR:
https://github.com/sjpadgett/openemr/pull/3

To work on 4.2.2 could be still done via the patch mechanism that could bring in:
patients/
public/assets/
interface/globals.php (with line that sets the  path to public/assets: https://github.com/bradymiller/openemr/blob/c8167a2809a8224184ab74347f262d01e379df48/interface/globals.php#L160)

**Pull request closed without merging**
