### PR TITLE
Telehealth Invitation with onetime integration

### PR DESCRIPTION
**Pull request by adunsulag**
Added a config option and integrated the telehealth invitation into the email.

I'm getting an ```Invalid URL``` option when I click on the link.  I'm stepping into it now to try and figure out what is going on.
If @sjpadgett you can look at how I'm using your service and see if you spot something I'm doing wrong, I'd appreciate it.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Looks okay to me. check the table to see what is stored for redirect.

**Comment by sjpadgett** [comment]
if using sendgrid turn off click tracking or ensure you use anchor in email html body

**Comment by adunsulag** [comment]
@sjpadgett I'm using Mailgun and just in the process of turning that off to see if that changes things.  The site id is where it's breaking.

**Comment by sjpadgett** [comment]
Are you send email as html with an anchor?

**Comment by adunsulag** [comment]
Figured out part of the problem was with my email template as I was adding additional parameters.    We were also missing an additional session variable in the one time setup.  I'm now processing the one time and it populates the session.  Yet, when it redirects to my module page it doesn't retain the session cookie and I can't figure out why.  

I've tried it in incognito thinking perhaps it was something with being logged in as an admin and a patient, but that didn't change anything.  I'll have to look more into it tomorrow as this is giving me quite the head scratcher.

**Comment by sjpadgett** [comment]
@adunsulag 
I've noticed on windows the link encoding generated from your normal email notification for a session is using windows path separators namely:
encoded link: ` 
https://opensourcedemr.us/interface/modules/custom_modules/oe-module-comlink-telehealth%5Cpublic%5Cindex-portal.php?action=launch_patient_session&pc_eid=31
`

**Comment by adunsulag** [comment]
That last part ?action=launch_patient_session&pc_eid=31 is what was messing up the url.  That is now fixed.  Discovered that my portal url was using an ip address and my site address was on localhost.  That was what was causing the cookie mismatch.  I'm adding some things to the globals config screen that will display an error to people if they have a mismatched portal hostname versus the FHIR hostname in case other people trigger the same problem.

**Pull request merged**
