### PR TITLE
Migrated standard bootstrap and support for right-to-left languages

### PR DESCRIPTION
**Pull request by bradymiller**
1. Migrated standard bootstrap to centralized asset
2. Removed several links that do not exist
3. Added initial support for right-to-left languages in the portal

### CODE REVIEW

**Comment by bradymiller** [comment]
These commits are testing well.
(btw, to see what a RTL language looks like, check out Hebrew; it looks nice on the individual screens, but there will be some additional minor work needed to make the main screen look nice in RTL mode(probably just override elements in style.css which matrix is good at doing), which can be done at a later date after the code is in the codebase)

**Comment by sjpadgett** [comment]
I've decided to pull the 12px bootstrap because it doesn't save that much screen space anyway.

**Comment by bradymiller** [comment]
thumbs up on that decision. let me know if you want me to bring in that commit to pull 12px and use the centralized bootstrap (it would only take me a second to do)

**Comment by sjpadgett** [comment]
please do

**Comment by sjpadgett** [comment]
If I can eek out a smooth way to pull phreeze, I am, then use just the backbone so I can keep modeling. Don't really see a need for rest here yet.

**Comment by bradymiller** [comment]
the leaner, the better :)

**Comment by bradymiller** [comment]
just placed the PR for the 12px bootstrap removal

**Pull request merged**
