### PR TITLE
Some datetimepicker work

### PR DESCRIPTION
**Pull request by bradymiller**
Got it working. Thanks for the help. I also removed the bootstrap datetimepicker since it's no longer used. This is testing well.

Some stuff I still plan to do:
1. Convert the reports, such as ledger to use the new picker (I will do this via the standard way, which am starting to do in the main codebase)
2. Sort out the picker in patients/patient/templates/OnsitePortalActivityListView.tpl.php which seems to be using the native bootstrap date picker and time picker (plan to analyze that later)

### CODE REVIEW

**Comment by sjpadgett** [comment]
Don't worry about patients/patient/templates/OnsitePortalActivityListView.tpl.php because it is not used. It is there in case I wanted to use it but I decided to generate a dynamic view instead. I originally gen'ed it because I needed the controller classes for audits. So controller models e.t.c. are used but I will delete the template.

**Comment by sjpadgett** [comment]
Also Brady, at some point I patched out all the bootstrap combo boxes and am using the standard html5 pull downs so that asset can go. I'll get to it sometime.

**Comment by sjpadgett** [comment]
Oh wait, now I remember, I planned to use that template for admin crud for portal audit cleanup in dashboard. Sorry I'm so forgetful these days, ole age. I'll clean it up and commit.

**Comment by bradymiller** [comment]
sounds good. I'll remove the bootstrap combo box links and assets.

**Pull request merged**
