### PR TITLE
add result to obseration, and allow a result to be a code

### PR DESCRIPTION
**Pull request by kchapple**
@sjpadgett this puts the result code in the assessment template

### CODE REVIEW

**Comment by sjpadgett** [comment]
This fixed ob_code problem, thanks

**Comment by kchapple** [comment]
@sjpadgett added the negation reason to procedure in previous commit

**Comment by kchapple** [comment]
@sjpadgett you can just merge these PRs into your branch as they come in if it's easier.

**Comment by kchapple** [comment]
@sjpadgett is this merged, can I close?

**Comment by sjpadgett** [comment]
@kchapple I already included these commits in my PR but I'll merged these to be safe.

**Comment by sjpadgett** [comment]
@bradymiller I check last PR for the changes in database! I don't understand how they didn't make it in!!!

**Comment by bradymiller** [comment]
@sjpadgett , don't worry. put a quick commit in to fix them up. go CQM!

**Comment by sjpadgett** [comment]
cool thank Brady. Keep an eye on me!

**Pull request merged**
